// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKY9rDvYF8h35eElv6q8x4FVuyU_dQkv8',
    appId: '1:393208576692:web:0f7f6f8a70e55307ac75e1',
    messagingSenderId: '393208576692',
    projectId: 'auth-firebase-a9034',
    authDomain: 'auth-firebase-a9034.firebaseapp.com',
    storageBucket: 'auth-firebase-a9034.appspot.com',
    measurementId: 'G-ZCSJ7S090E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgYLaZX_kM_61orvhOkC2-dcer1n7f94',
    appId: '1:393208576692:android:d1a1d292214d22bbac75e1',
    messagingSenderId: '393208576692',
    projectId: 'auth-firebase-a9034',
    storageBucket: 'auth-firebase-a9034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTD6PZ1mPHsoaCxucrGhOKXJtS5nCotG8',
    appId: '1:393208576692:ios:f0b1f78100bdd422ac75e1',
    messagingSenderId: '393208576692',
    projectId: 'auth-firebase-a9034',
    storageBucket: 'auth-firebase-a9034.appspot.com',
    androidClientId: '393208576692-822cprmhddi6s9hef34hd0ienmb24tck.apps.googleusercontent.com',
    iosClientId: '393208576692-nrg203lbjpcfeirrssck5ggav5pldtmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookBala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTD6PZ1mPHsoaCxucrGhOKXJtS5nCotG8',
    appId: '1:393208576692:ios:f0b1f78100bdd422ac75e1',
    messagingSenderId: '393208576692',
    projectId: 'auth-firebase-a9034',
    storageBucket: 'auth-firebase-a9034.appspot.com',
    androidClientId: '393208576692-822cprmhddi6s9hef34hd0ienmb24tck.apps.googleusercontent.com',
    iosClientId: '393208576692-nrg203lbjpcfeirrssck5ggav5pldtmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookBala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKY9rDvYF8h35eElv6q8x4FVuyU_dQkv8',
    appId: '1:393208576692:web:eae7aeca7b7c1e19ac75e1',
    messagingSenderId: '393208576692',
    projectId: 'auth-firebase-a9034',
    authDomain: 'auth-firebase-a9034.firebaseapp.com',
    storageBucket: 'auth-firebase-a9034.appspot.com',
    measurementId: 'G-BCTMGEB89Y',
  );
}
